Repository synthesizer-project/synthesizer, pull requests merged in 2024-07, with the labels that each got.

#662 Removing automatic bolometric luminosity calculation
  src/synthesizer/emission_models/agn/unified_agn.py
  src/synthesizer/sed.py
Labels: Spectra/SED

#661 Enabling the discarding of spectra for memory savings
  docs/source/emission_models/custom_models.ipynb
  docs/source/photometry/galaxy_phot.ipynb
  docs/source/spectra/galaxy.ipynb
  src/synthesizer/base_galaxy.py
  src/synthesizer/emission_models/base_model.py
Labels: Performance, EmissionModels

#656 Implemented methods to return "Characteristic radii"
  docs/source/components/gas.ipynb
  docs/source/components/stars.ipynb
  docs/source/photometry/galaxy_phot.ipynb
  src/synthesizer/particle/galaxy.py
  src/synthesizer/particle/particles.py
  src/synthesizer/particle/stars.py
  src/synthesizer/photometry.py
  src/synthesizer/units.py
  src/synthesizer/utils/ascii_table.py
Labels: enhancement, particle

#666 Ensuring emissions aren't prematurely deleted
  src/synthesizer/emission_models/base_model.py
Labels: bug, EmissionModels

#669 Remove multiple returns for non-reprocessed grid in PacmanEmission
  src/synthesizer/emission_models/stellar/pacman_model.py
  src/synthesizer/grid.py
Labels: bug, grid, EmissionModels

#673 Added an escape fractionless `PacmanEmission` called `ScreenEmission`
  docs/source/emission_models/premade_models/stellar_models.ipynb
  src/synthesizer/emission_models/__init__.py
  src/synthesizer/emission_models/stellar/__init__.py
  src/synthesizer/emission_models/stellar/pacman_model.py
Labels: EmissionModels

#667 Improved the emission model docs to include emitter info and parameter overides
  docs/source/emission_models/custom_models.ipynb
  docs/source/spectra/blackholes.ipynb
  docs/source/spectra/galaxy.ipynb
  docs/source/spectra/stars.ipynb
  src/synthesizer/emission_models/__init__.py
  src/synthesizer/emission_models/base_model.py
  src/synthesizer/sed.py
Labels: documentation, EmissionModels

#676 Introduced tau conversions.
  src/synthesizer/conversions.py
Labels: Conversions

#663 Added some extra defaults and controls to the installation process
  docs/source/advanced/config_options.rst
  setup.py
Labels: Installation

#665 Fixed assignment of dust emission and total spectra
  docs/source/emission_models/combined_models.ipynb
  docs/source/emission_models/premade_models/stellar_models.ipynb
  src/synthesizer/emission_models/stellar/pacman_model.py
Labels: EmissionModels

#664 Removed conflicting Quantites from an Sed
  src/synthesizer/sed.py
Labels: Spectra/SED, Clean up

#674 Added a method to explicitly list spectra to save
  docs/source/spectra/galaxy.ipynb
  src/synthesizer/emission_models/base_model.py
Labels: EmissionModels

#668 Fix parametric young stars masks
  src/synthesizer/particle/stars.py
Labels: bug, particle, Spectra/SED

#678 Fix doc build example failures
  docs/CONTRIBUTING.md
  docs/Makefile
  docs/source/advanced/creating_grids.rst
  docs/source/advanced/units.ipynb
  docs/source/attenuation/dust_attenuation.ipynb
  docs/source/conf.py
  docs/source/emission_models/premade_models/agn_models.ipynb
  docs/source/emission_models/premade_models/common_models.ipynb
  docs/source/filters/filters.rst
  docs/source/filters/filters_example.ipynb
  docs/source/imaging/parametric_data_cube.ipynb
  docs/source/imaging/parametric_imaging.ipynb
  docs/source/imaging/particle_data_cube.ipynb
  docs/source/imaging/particle_imaging.ipynb
  docs/source/imaging/property_maps.ipynb
  docs/source/lines/galaxy_lines.ipynb
  docs/source/lines/grid_lines.ipynb
  docs/source/photometry/photometry_example.ipynb
  examples/cosmo/plot_cosmo_example.py
  examples/cosmo/plot_parametric_young_stars.py
  examples/cosmo/plot_test_aperture_mask.py
  examples/cosmo/plot_test_los_spectra.py
  examples/cosmo/test_parametric_young_stars.py
  examples/grids/plot_line_cont.py
  examples/imaging/image_addition.py
  examples/imaging/plot_image_addition.py
  examples/parametric/generate_lines.py
  examples/parametric/generate_sed.py
  examples/parametric/plot_generate_lines.py
  pyproject.toml
  src/synthesizer/emission_models/attenuation/dust.py
  src/synthesizer/imaging/image.py
  src/synthesizer/load_data/load_bluetides.py
  src/synthesizer/load_data/load_camels.py
  src/synthesizer/load_data/load_illustris.py
  src/synthesizer/particle/stars.py
Labels: documentation, examples

#679 BUGFIX: Fixed a bad error in line attenuation
  src/synthesizer/line.py
Labels: bug, Lines

#680 BUGFIX: Ensuring a `Grid` always contains attributes even if they are None
  src/synthesizer/grid.py
Labels: bug, grid

#675 Introduced helper methods for clearing out emissions on a `Galaxy` and components
  docs/source/spectra/blackholes.ipynb
  docs/source/spectra/stars.ipynb
  src/synthesizer/base_galaxy.py
  src/synthesizer/components/blackhole.py
  src/synthesizer/components/stellar.py
Labels: Photometry, Spectra/SED, Galaxy, Lines, Components

#688 BUGFIX: Removed broken args when compiling without openmp
  src/synthesizer/extensions/column_density.c
Labels: bug, Installation

#685 Introduced ability to get limit test data downloads
  src/synthesizer/download_data.py
Labels: Data

#690 BUGFIX: Fixed `PacmanEmission` intrinsic model
  src/synthesizer/emission_models/stellar/pacman_model.py
Labels: bug, EmissionModels

#691 Changed nebular nomenclature to birth to be more accurate in `BimodalPacmanEmission`
  docs/source/emission_models/combined_models.ipynb
  docs/source/emission_models/premade_models/stellar_models.ipynb
  docs/source/lines/galaxy_lines.ipynb
  docs/source/photometry/galaxy_phot.ipynb
  docs/source/spectra/galaxy.ipynb
  examples/cosmo/plot_cosmo_example.py
  examples/parametric/plot_sed.py
  src/synthesizer/emission_models/stellar/pacman_model.py
Labels: documentation, EmissionModels
