Repository synthesizer-project/synthesizer, pull requests merged in 2025-05, with the labels that each got.

#912 Further modularising the Pipeline observables
  conftest.py
  docs/source/pipelines/pipeline_example.ipynb
  src/synthesizer/base_galaxy.py
  src/synthesizer/components/component.py
  src/synthesizer/instruments/filters.py
  src/synthesizer/instruments/instrument_collection.py
  src/synthesizer/pipeline/pipeline.py
  src/synthesizer/pipeline/pipeline_io.py
  tests/test_pipeline.py
Labels: Instruments, Pipeline

#921 Bring particle -> integrated sum inside C machinery
  src/synthesizer/emission_models/extractors/extractor.py
  src/synthesizer/emission_models/operations.py
  src/synthesizer/extensions/column_density.c
  src/synthesizer/extensions/integrated_spectra.c
  src/synthesizer/extensions/integration.c
  src/synthesizer/extensions/particle_spectra.c
  src/synthesizer/extensions/property_funcs.h
  src/synthesizer/extensions/sfzh.c
  src/synthesizer/extensions/weights.c
  src/synthesizer/extensions/weights.h
  src/synthesizer/imaging/extensions/image.c
  src/synthesizer/imaging/extensions/spectral_cube.c
  tests/test_extractors.py
  tests/test_spectra.py
  tests/test_vel_shift.py
Labels: particle, Performance

#923 Updating the link to the grid directory
  docs/source/grids/grids.rst
Labels: documentation

#924 Fix unknown pleasures method
  src/synthesizer/imaging/image.py
Labels: Fun

#925 Fixed a horrid typo that slipped under the radar
  src/synthesizer/particle/particles.py
Labels: bug

#926 Fix units on zero valued derived properties
  src/synthesizer/particle/galaxy.py
Labels: bug, Loaders

#927 Introducing some premade instruments and related machinery
  .github/workflows/python-app.yml
  .github/workflows/static.yml
  docs/source/index.rst
  docs/source/instrumentation/instrument_example.ipynb
  docs/source/instrumentation/premade_instruments.ipynb
  src/instrument_generation/get_instruments.py
  src/synthesizer/downloader/_data_ids.yml
  src/synthesizer/downloader/database.py
  src/synthesizer/downloader/downloader.py
  src/synthesizer/exceptions.py
  src/synthesizer/instruments/__init__.py
  src/synthesizer/instruments/filters.py
  src/synthesizer/instruments/instrument.py
  src/synthesizer/instruments/instrument_cache/README
  src/synthesizer/instruments/premade.py
  src/synthesizer/instruments/utils.py
Labels: Data, Instruments
